config/routes.rb
Rails.application.routes.draw do

  scope module: 'web' do
    root to: 'tasks#index'
    resources :tasks, only: [:index]

    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
    get "logout", to: "sessions#destroy", as: "logout"
    get "login", to: "sessions#new", as: "login"
    get "signup", to: "users#new", as: "signup"

    namespace :admin do
      resources :tasks
      resources :users, only: [:index]
    end

    namespace :members do
      resources :tasks
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  validates :name, :user_id, presence: true

  scope :user_tasks, -> (user_id) { where user_id: user_id }

  def as_json(options = {})
    TaskSerializer.new(self).as_json(root: false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, length: { minimum: 6 }, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/web/admin/tasks_controller.rb
class Web::Admin::TasksController < Web::ApplicationController
  before_action :authenticate
  before_action :load_task, only: [:destroy, :update]

  def index
    @tasks = Task.all.as_json
  end

  def destroy
    @task.destroy
    head :no_content
  end

  def create
    @task = Task.new(task_params.merge(user: current_user))
    if @task.save
      render json: @task, root: false
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  def update
    if @task.update(task_params)
      render json: @task, root:false
    else
      render json: { errors: @task.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def load_task
    @task = Task.find_by(id: params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :user_id)
  end
end

app/controllers/web/admin/users_controller.rb
class Web::Admin::UsersController < Web::ApplicationController
  before_action :authenticate, only: [:index]

  def index
    if is_admin?
      render json: @users = User.select('id', 'email').as_json, root: false
    else
      render json: { errors: 'You can not have permission for this operation' }, status: :unauthorized
    end
  end

  private

  def is_admin?
    current_user && (current_user.role == 'admin')
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController

  private

  helper_method :current_user, :signed_in?

  def authenticate
    unless signed_in?
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    current_user.present?
  end
end

app/controllers/web/members/tasks_controller.rb
class Web::Members::TasksController < Web::ApplicationController
  before_action :authenticate
  before_action :load_task, only: [:destroy, :update, :show]
  before_action :verify_user, only: [:destroy, :update]

  def index
    @tasks = Task.user_tasks(current_user).as_json
  end

  def create
    @task = Task.new(task_params.merge(user: current_user))
    if @task.save
      render json: @task, root: false
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    if @task.update(task_params)
      render json: @task, root:false
    else
      render json: { errors: @task.errors.full_messages },
              status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    head :no_content
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

  def load_task
    @task = Task.find_by(id: params[:id])
  end

  def verify_user
    unless valid_user?
      render json: { errors: 'You can not have permission for this operation' },
              status: :unauthorized
    end
  end

  def valid_user?
    current_user && (current_user.id == @task.user_id)
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: session_params[:email])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_user
    else
      @error_message = "Invalid email/password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

  def redirect_user
    case current_user.role
    when 'user'
      redirect_to members_tasks_path
    when 'admin'
      redirect_to admin_tasks_path
    end
  end
end

app/controllers/web/tasks_controller.rb
class Web::TasksController < Web::ApplicationController

  def index
    @tasks = Task.all.as_json
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to members_tasks_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def to_local_date(utc_date)
    utc_date.in_time_zone.strftime("%d/%m/%Y %H:%M")
  end
end

app/helpers/web/tasks_helper.rb
module Web::TasksHelper
end

app/views/layouts/application.html.slim
html
  head
    title Task manager for VoltMobi
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    .container-fluid
      nav.navbar.navbar-default
        .container-fluid
          .navbar-brand
            - if signed_in?
              = link_to 'Home', members_tasks_path
            - else
              = link_to 'Home', root_path
          ul.nav.navbar-nav.navbar-right
            - if signed_in?
              li = link_to 'Log out', logout_path
            - else
              li = link_to 'Log in', login_path
              li = link_to 'Register', signup_path

    .col-md-10.main 
      = yield

  footer.navbar-fixed-bottom.row-fluid
    .navbar-inner
      .container
        | by Tesevich Alexander
        =<> link_to 'Github', 'https://github.com/alx-t'
                                                                                                                                                                                

app/views/web/admin/tasks/index.html.slim
= react_component 'Tasks', { tasks: @tasks, type: 'admin', user_id: current_user.id }

app/views/web/members/tasks/index.html.slim
= react_component 'Tasks', { tasks: @tasks, type: 'user', user_id: current_user.id }

app/views/web/members/tasks/show.html.slim
h3
  | Task #
  = @task.id
br
h4
  = @task.name
h4
  = @task.description
br
| Created at:
=<> to_local_date @task.created_at
br
- if @current_user.role == 'admin'
  | Assigned to:
  =<> @task.user.email

app/views/web/tasks/index.html.slim
= react_component 'Tasks', { tasks: @tasks, type: 'common' }

app/views/web/users/_form.html.slim
= simple_form_for user do |f|
  - if user.errors.any?
    .error-messages.alert-danger
      ul
        - for message in user.errors.full_messages 
          li = message
  = f.input :email, label: 'Email', required: true
  = f.input :password, label: 'Password'
  = f.input :password_confirmation, label: 'Password confirmation'
  = f.submit 'Create user',  class: 'btn btn-block btn-primary'

app/views/web/users/new.html.slim
.col-sm-offset-3.col-sm-6
  .panel.panel-default
    .panel-heading 
      h3 Sign up
    .panel-body
      = render 'form', user: @user